import type { Metadata } from "next";
import { Golos_Text, Spectral, Geist_Mono } from "next/font/google";
import "./globals.css";

const golosText = Golos_Text({
  variable: "--font-geist-sans",
  subsets: ["latin", "cyrillic"],
});

const spectral = Spectral({
  variable: "--font-playfair-display",
  weight: ["500", "600"],
  subsets: ["latin", "cyrillic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${golosText.variable} ${spectral.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
